import { BASE_PATH } from '@/config/site';
import { EXAMPLE_JOB_DESCRIPTIONS } from '@/content/example-jobs';

/** Downloadable example resumes, generated by `pnpm fixtures` into public/examples. */
export const EXAMPLE_FILES = {
  'senior-engineer': {
    label: 'Senior engineer',
    format: 'PDF',
    path: `${BASE_PATH}/examples/avery-lindqvist-resume.pdf`,
    fileName: 'avery-lindqvist-resume.pdf',
    mimeType: 'application/pdf',
    job: EXAMPLE_JOB_DESCRIPTIONS['senior-full-stack'],
  },
  'frontend-developer': {
    label: 'Frontend developer',
    format: 'DOCX',
    path: `${BASE_PATH}/examples/jordan-okafor-cv.docx`,
    fileName: 'jordan-okafor-cv.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    job: EXAMPLE_JOB_DESCRIPTIONS['frontend-developer'],
  },
} as const;

export type ExampleId = keyof typeof EXAMPLE_FILES;

export function isExampleId(value: string | null): value is ExampleId {
  return value !== null && value in EXAMPLE_FILES;
}

export async function loadExampleFile(id: ExampleId): Promise<File> {
  const example = EXAMPLE_FILES[id];
  const response = await fetch(example.path);
  if (!response.ok) throw new Error('The example resume could not be loaded.');
  return new File([await response.blob()], example.fileName, { type: example.mimeType });
}
